// <auto-generated />
using API_KTX_MANAGEMENT.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_KTX_MANAGEMENT.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201206080323_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_KTX_MANAGEMENT.Model.Dien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaDien");

                    b.HasKey("Id");

                    b.ToTable("Dien");
                });

            modelBuilder.Entity("API_KTX_MANAGEMENT.Model.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDien");

                    b.Property<int>("IdNhanVien");

                    b.Property<int>("IdNuoc");

                    b.Property<int>("IdRoom");

                    b.Property<string>("NgayLap");

                    b.Property<int>("SoDienCu");

                    b.Property<int>("SoDienMoi");

                    b.Property<int>("SoNuocCu");

                    b.Property<int>("SoNuocMoi");

                    b.Property<double>("ThanhTien");

                    b.HasKey("Id");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("API_KTX_MANAGEMENT.Model.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdNhanVien");

                    b.Property<int>("IdSinhVien");

                    b.Property<string>("NgayBatDau");

                    b.Property<string>("NgayKetThuc");

                    b.Property<string>("NgayLamDon");

                    b.Property<string>("NgayLap");

                    b.Property<int>("TinhTrang");

                    b.HasKey("Id");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("API_KTX_MANAGEMENT.Model.Khu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenKhu");

                    b.HasKey("Id");

                    b.ToTable("Khu");
                });

            modelBuilder.Entity("API_KTX_MANAGEMENT.Model.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChucVu");

                    b.Property<string>("DiaChi");

                    b.Property<int>("GioiTinh");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("API_KTX_MANAGEMENT.Model.Nuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaNuoc");

                    b.HasKey("Id");

                    b.ToTable("Nuoc");
                });

            modelBuilder.Entity("API_KTX_MANAGEMENT.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdKhu");

                    b.Property<string>("MoTa");

                    b.Property<int>("SoLuong");

                    b.Property<int>("SoLuongToiDa");

                    b.Property<string>("TenPhong");

                    b.Property<int>("TinhTrang");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("API_KTX_MANAGEMENT.Model.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GioiTinh");

                    b.Property<string>("MSSV");

                    b.Property<string>("Name");

                    b.Property<string>("NgaySinh");

                    b.Property<string>("Passport");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
